dist: trusty
sudo: required

language: cpp
compiler:
    - gcc
    - clang

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

        packages:
            - g++-6
            - lcov
            - libgtest-dev
            - cmake
            - cmake-data
            - vtk6 
            - libvtk6-dev 
            - libpq-dev 
            - libinsighttoolkit3-dev
            - itk3
before_script:
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script: 
    - mkdir -p build
    - cd build
    - cmake .. 
    - cmake --build .

